F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\common.vh
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\common\\dff.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\common\\mux2.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\common\\mux4.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\EX\\ALU.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\EX\\ALU_control.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\EX\\br_control.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\EX\\EX.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\EX\\left_shift.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\EX\\status_reg.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\ID\\ID.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\ID\\reg_file.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\ID\\sign_extend.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\IF\\IF.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\IF\\inst_mem.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\MEM\\data_mem.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\TEST\\ALU_control_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\TEST\\ALU_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\TEST\\control_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\TEST\\data_mem_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\TEST\\EX_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\TEST\\ID_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\TEST\\IF_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\TEST\\inst_mem_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\TEST\\reg_file_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\TEST\\sign_extend_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\TEST\\TOP_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\TEST\\write_back_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\TOP\\control.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\TOP\\datapath.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\TOP\\TOP.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve\\WB\\write_back.v
