F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\common.vh
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\common\\dff.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\common\\mux2.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\common\\mux4.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\EX\\ALU.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\EX\\ALU_control.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\EX\\EX.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\EX\\left_shift.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\EX\\status_reg.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\ID\\ID.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\ID\\reg_file.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\ID\\sign_extend.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\IF\\IF.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\IF\\inst_mem.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\MEM\\br_control.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\MEM\\data_mem.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TEST\\ALU_control_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TEST\\ALU_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TEST\\control_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TEST\\data_mem_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TEST\\EX_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TEST\\ID_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TEST\\IF_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TEST\\inst_mem_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TEST\\reg_file_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TEST\\sign_extend_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TEST\\TOP_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TEST\\write_back_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TOP\\control.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TOP\\PipelineCPU.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TOP\\PipelineDatapath.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TOP\\PipelineTOP.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TOP\\SingleCycleCPU.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TOP\\SingleCycleDatapath.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\TOP\\SingleCycleTOP.v
F:\\Files\\courses\\Digital_IC\\hw\\prj_improve2\\WB\\write_back.v
