F:\\Files\\courses\\Digital_IC\\hw\\prj\\common.vh
F:\\Files\\courses\\Digital_IC\\hw\\prj\\common\\dff.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\common\\mux2.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\common\\mux4.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\EX\\ALU.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\EX\\ALU_control.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\EX\\br_control.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\EX\\EX.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\EX\\left_shift.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\EX\\status_reg.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\ID\\ID.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\ID\\reg_file.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\ID\\sign_extend.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\IF\\IF.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\IF\\inst_mem.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\MEM\\data_mem.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\TEST\\ALU_control_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj\\TEST\\ALU_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj\\TEST\\control_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj\\TEST\\data_mem_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj\\TEST\\EX_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj\\TEST\\ID_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj\\TEST\\IF_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj\\TEST\\inst_mem_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj\\TEST\\reg_file_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj\\TEST\\sign_extend_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj\\TEST\\TOP_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj\\TEST\\write_back_tb.sv
F:\\Files\\courses\\Digital_IC\\hw\\prj\\TOP\\control.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\TOP\\datapath.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\TOP\\TOP.v
F:\\Files\\courses\\Digital_IC\\hw\\prj\\WB\\write_back.v
